samples: config/samples.tsv

units: config/units.tsv

guides: media.addgene.org/cms/filer_public/71/a8/71a81179-7a62-4d75-9b53-236e6f6b7d4d/tkov3_guide_sequence.xlsx

bagel_zip: github.com/hart-lab/bagel/archive/refs/heads/master.zip

control_genotype: WT

species: human

trim: 0

max_length: 20
