$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  samples:
    type: string
  units:
    type: string

  guides:
    type: string 

  trim:
    type: integer

  max_length:
    type: integer

required:
  - samples
  - units
  - guides
