$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  samples:
    type: string
    description: path to your samples table. Does not need to be edited if you intend to edit config/samples.tsv file instead.

  units:
    type: string
    description: path to your units table. Does not need to be edited if you intend to edit config/units.tsv file instead.

  guides:
    type: string
    description: URL (omitting the http:// prefix) to excel spreadsheet of guide sequences. Currently those in the format of the Toronto knockout libraries are supported (e.g. TKOv3 and mTKO).

  control_genotype:
    type: string
    description: control genotype for synthetic lethal/suppressor gene identification. If provided, a regression analysis of other genotypes will be performed comparing BAGEL and JACKS scores against this genotype. Assumes matching timepoints for each genotype.

  bagel_zip:
    type: string
    description: URL of BAGEL github repository.

  trim:
    type: integer
    description: Optional parameter to specify the number of nucleotides to trim from the start of each read in your FASTQ files.

  max_length:
    type: integer
    description: Optional parameter to specify the length of sequence to keep from your FASTQ files (i.e. if you need to trim from the 3' ends of your sequences).

  species:
    type: string
    description: Used to automatically determine which core essential and negative control gene sets to use. Either human or mouse are supported. Ignored if bagel_ess_genes and bagel_neg_genes are specified. Default = human.

  bagel_ess_genes:
    type: string
    description: Path to text file containing core essential genes relevant to your study. File must contain gene symbols as the first (or only) whitespace separated column.

  bagel_neg_genes:
    type: string
    description: Path to text file containing negative control non-essential genes relevant to your study. File must contain gene symbols as the first (or only) whitespace separated column.

required:
  - samples
  - units
  - guides
  - bagel_zip
